### ISSUE TITLE
Crash after using the booster command

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/BoosterManager#2]
I want to craft booster packs on a few accounts.

After calling `!booster ASF XXX`, where `XXX` is the appID of the game of interest, ASF would crash:
- only when using this plugin (`Citrinate/BoosterManager`),
- not with the original one (`Ryzhehvost/BoosterCreator`).

```
2022-12-11 10:18:17|dotnet-2864|FATAL|ASF|OnUnhandledException() System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'steamID')
   at ArchiSteamFarm.Steam.Bot.SendMessage(UInt64 steamID, String message)
   at BoosterManager.BoosterHandler.SendStatusReport(Bot respondingBot, UInt64 recipientSteamID)
   at BoosterManager.BoosterHandler.<PerpareStatusReport>b__19_0(Object e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

https://github.com/Citrinate/BoosterManager/blob/af0273c9f0a54c2b3a4804c13ac4fe5b26dd74a4/BoosterManager/Handlers/BoosterHandler.cs#L129

---

This also happens when using only one account (the first in the list) and calling:
- either `!booster XXX`,
- or `!booster BOT XXX`, where `BOT` is the name of the account.

**Comment by Citrinate** [comment]
Thanks for the report

Are you sending these commands through Steam chat, or are you using ASF-ui?

This error might be dependent on which account you're sending the `!booster` command to.  You say this is an issue with only some accounts?  If an account you don't have the issue with is `GoodBot`, and an account you do have the issue with is `BadBot`, then I'm wondering if you send the command `!booster BadBot XXX` to `GoodBot`, does the issue occur?

I'm also seeing that this could happen if you send the `!booster` command to accounts that Steam classifies as either "Individual" or "ConsoleUser".  Do you think either of those might apply to the accounts you're having issues with?  I'm guessing a "ConsoleUser" account was an account created on a Playstation, and here's a possible description of an "Individual" account (I'm not sure how accurate it is):

>Users of an "Individual" account are temporarily referred to as having a "Pending" account, which has a textual representation of "STEAM_ID_PENDING" until their account credentials are verified with Steam's authentication servers, a process usually complete by the time a server is fully connected to. Accounts of the type "Invalid" have a textual representation of "UNKNOWN" and are used for bots and accounts which do not belong to another class.

If you'd like some gems for testing, feel free to add me [on Steam](https://steamcommunity.com/id/Citrinate/).

**Comment by woctezuma** [comment]
> Are you sending these commands through Steam chat, or are you using ASF-ui?

I use Windows, and I send the commands via the ASF window started by `ArchiSteamFarm.cmd`.

![Terminal](https://i.ibb.co/VpP6Qzy/2022-12-11-19-11-19.png) (expires in 7 days)

> You say this is an issue with only some accounts?

I have access to 4 non-limited accounts, and the issue happens with all of them.

> I'm also seeing that this could happen if you send the !booster command to accounts that Steam classifies as either "Individual" or "ConsoleUser". Do you think either of those might apply to the accounts you're having issues with?

I don't think so. All of these accounts were created on PC.

**Comment by woctezuma** [comment]
I did not mention that I use other plugins. I will try without other plugins.

![Plugins](https://i.ibb.co/Nrmf9Vt/2022-12-11-19-21-05.png)
(the image expires in 7 days)

**Edit: The issue happens nonetheless.**

![Plugins](https://i.ibb.co/nM6NS51/2022-12-11-19-25-27.png)
(the image expires in 7 days)

![Error](https://i.ibb.co/5hZK0yg/2022-12-11-19-24-01.png)
(the image expires in 7 days)

**Comment by Citrinate** [comment]
I'm able to reproduce the issue using the ASF console.  This build should fix things: [BoosterManager.zip](https://github.com/Citrinate/BoosterManager/files/10203128/BoosterManager.zip)

**Comment by woctezuma** [comment]
Thank you, this works great!
