### ISSUE TITLE
6.1 build crashes with ASF-win-x64

### ISSUE THREAD

**Issue by Nuklon** [Citrinate/BoosterManager#27]
6.0 and before always worked fine with the win-x64 build, but now it seems the generic ASF is required. It crashes with this:

```txt
Application: ArchiSteamFarm.exe
CoreCLR Version: 9.0.24.52809
.NET Version: 9.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException: Attempted to access a missing method.
   at BoosterManager.StatusReporter.Report(Bot reportingBot, String report, Boolean suppressDuplicateMessages, Boolean log)
   at BoosterManager.BoosterJob.OnBoosterInfosUpdated(Dictionary`2 boosterInfos)
   at BoosterManager.BoosterQueue.UpdateBoosterInfos()
   at BoosterManager.BoosterQueue.Run()
   at BoosterManager.BoosterQueue.<.ctor>b__22_0(Object e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

or

```txt
Application: ArchiSteamFarm.exe
CoreCLR Version: 9.0.24.52809
.NET Version: 9.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException: Attempted to access a missing method.
   at BoosterManager.BoosterDatabase.SetLastCraft(UInt32 appID, DateTime craftTime)
   at BoosterManager.Booster.SetWasCrafted()
   at BoosterManager.BoosterQueue.<>c__DisplayClass33_0.<VerifyCraftBoosterError>g__handler|0(Dictionary`2 boosterInfos)
   at BoosterManager.BoosterQueue.UpdateBoosterInfos()
   at BoosterManager.BoosterQueue.Run()
   at BoosterManager.BoosterQueue.<.ctor>b__22_0(Object e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by Citrinate** [comment]
These crashes should be fixed now in V2.10.2.1
