### ISSUE TITLE
Failure after ASF updated to 5.4.8.3

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/BoosterManager#6]
```
2023-08-01 09:35:34|dotnet-5928|ERROR|ASF|InitPlugins() Échec dû à une erreur : BoosterManager, Version=2.4.1.0, Culture=neutral, PublicKeyToken=null
2023-08-01 09:35:34|dotnet-5928|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'EType' from assembly 'ArchiSteamFarm, Version=5.4.8.3, Culture=neutral, PublicKeyToken=504f46588cc351a9'.
Could not load type 'EType' from assembly 'ArchiSteamFarm, Version=5.4.8.3, Culture=neutral, PublicKeyToken=504f46588cc351a9'.
Could not load type 'EType' from assembly 'ArchiSteamFarm, Version=5.4.8.3, Culture=neutral, PublicKeyToken=504f46588cc351a9'.
Could not load type 'ArchiSteamFarm.Steam.Security.Confirmation' from assembly 'ArchiSteamFarm, Version=5.4.8.3, Culture=neutral, PublicKeyToken=504f46588cc351a9'.
Could not load type 'ArchiSteamFarm.Steam.Security.Confirmation' from assembly 'ArchiSteamFarm, Version=5.4.8.3, Culture=neutral, PublicKeyToken=504f46588cc351a9'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.TypeLoadException: Could not load type 'EType' from assembly 'ArchiSteamFarm, Version=5.4.8.3, Culture=neutral, PublicKeyToken=504f46588cc351a9'.
System.TypeLoadException: Could not load type 'EType' from assembly 'ArchiSteamFarm, Version=5.4.8.3, Culture=neutral, PublicKeyToken=504f46588cc351a9'.
System.TypeLoadException: Could not load type 'EType' from assembly 'ArchiSteamFarm, Version=5.4.8.3, Culture=neutral, PublicKeyToken=504f46588cc351a9'.
System.TypeLoadException: Could not load type 'ArchiSteamFarm.Steam.Security.Confirmation' from assembly 'ArchiSteamFarm, Version=5.4.8.3, Culture=neutral, PublicKeyToken=504f46588cc351a9'.
System.TypeLoadException: Could not load type 'ArchiSteamFarm.Steam.Security.Confirmation' from assembly 'ArchiSteamFarm, Version=5.4.8.3, Culture=neutral, PublicKeyToken=504f46588cc351a9'.
```

**Comment by Domjul** [comment]
Hello! I have the same error message.

**Comment by woctezuma** [comment]
Thank you! 🥳
